### ISSUE TITLE
Use in Unity

### ISSUE THREAD

**Issue by thislookshard** [aybe/aubio.net#8]
Hey I don't know how possible this is, but have you ever tried using this library in Unity? I've been trying to find a good audio analysis library for Unity for months and have not have much luck with C# libraries, but aubio looks to be one of the best.  I know it won't work "out of the box" for it, and I'm the most proficient when it comes to Aubio itself, so I was wondering if you have any idea on how to make this compatible with Unity projects?

**Comment by aybe** [comment]
No I haven't. 

Beside the fact that DLL imports shall not have an extension, I really see no reason why it wouldn't work.

https://docs.unity3d.com/Manual/NativePlugins.html

And of course, aubio should be compilable for the relevant platform you plan to use !
